server:
  port: 8080
spring:
  h2:
    console:
      enabled: true	
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: 
      driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

security:
  config:
    prefix: "Bearer "
    key: "3288b5a38e055df0ddf0fc36c2bab5b59b5ac2d4314c01874c260f193c7b79f2"
    expiration: 3600000